// Single source of truth for IPC channel names.

export const IPC = {
  // settings
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  // imports
  IMPORTS_DETECT: 'imports:detect',
  IMPORTS_PREVIEW: 'imports:preview',
  IMPORTS_RUN: 'imports:run',
  IMPORTS_LIST: 'imports:list',
  IMPORTS_REVERT: 'imports:revert',
  IMPORTS_PICK_FILE: 'imports:pickFile',
  // sales
  SALES_LIST: 'sales:list',
  SALES_GET: 'sales:get',
  SALES_UPDATE: 'sales:update',
  SALES_TOGGLE_DECLARABLE: 'sales:toggleDeclarable',
  SALES_RECLASSIFY: 'sales:reclassify',
  SALES_CREATE_MANUAL: 'sales:createManual',
  SALES_LINK_STOCK: 'sales:linkStock',
  SALES_CREATE_STOCK_FROM_SALE: 'sales:createStockFromSale',
  SALES_AUDIT: 'sales:audit',
  SALES_DELETE: 'sales:delete',
  // declarations
  DECLARATIONS_LIST_PERIODS: 'declarations:listPeriods',
  DECLARATIONS_SUMMARY: 'declarations:summary',
  DECLARATIONS_FIRST_DECLARATION: 'declarations:firstDeclaration',
  DECLARATIONS_EXPORT_RECETTES: 'declarations:exportRecettes',
  DECLARATIONS_MARK_DECLARED: 'declarations:markDeclared',
  // contribution rates
  RATES_LIST: 'rates:list',
  RATES_UPSERT: 'rates:upsert',
  RATES_VERIFICATION_STATUS: 'rates:verificationStatus',
  RATES_MARK_VERIFIED: 'rates:markVerified',
  // dashboard
  DASHBOARD_OVERVIEW: 'dashboard:overview',
  // stock
  STOCK_LIST: 'stock:list',
  STOCK_GET: 'stock:get',
  STOCK_CREATE_MANUAL: 'stock:createManual',
  STOCK_UPDATE: 'stock:update',
  STOCK_MOVE_OUT: 'stock:moveOut',
  STOCK_MOVE_IN: 'stock:moveIn',
  STOCK_MOVEMENTS: 'stock:movements',
  STOCK_RESERVE: 'stock:reserve',
  STOCK_BULK_LOCATION: 'stock:bulkLocation',
  STOCK_FIND_BY_SKU: 'stock:findBySku',
  STOCK_OVERVIEW: 'stock:overview',
  STOCK_SPLIT_LOT: 'stock:splitLot',
  STOCK_DELETE: 'stock:delete',
  // purchases
  PURCHASES_LIST: 'purchases:list',
  PURCHASES_CREATE_MANUAL: 'purchases:createManual',
  PURCHASES_UPDATE: 'purchases:update',
  PURCHASES_DELETE: 'purchases:delete',
  // expenses
  EXPENSES_LIST: 'expenses:list',
  EXPENSES_CREATE: 'expenses:create',
  EXPENSES_UPDATE: 'expenses:update',
  EXPENSES_DELETE: 'expenses:delete',
  EXPENSES_OVERVIEW: 'expenses:overview',
  // boosts
  BOOSTS_LIST: 'boosts:list',
  BOOSTS_CREATE: 'boosts:create',
  BOOSTS_UPDATE: 'boosts:update',
  BOOSTS_DELETE: 'boosts:delete',
  BOOSTS_ASSIGN: 'boosts:assign',
  // documents
  DOCS_LIST: 'docs:list',
  DOCS_ADD: 'docs:add',
  DOCS_ADD_FROM_PATHS: 'docs:addFromPaths',
  DOCS_OPEN: 'docs:open',
  DOCS_LINK: 'docs:link',
  DOCS_UNLINK: 'docs:unlink',
  DOCS_LINKS_FOR: 'docs:linksFor',
  DOCS_PICK_FILES: 'docs:pickFiles',
  DOCS_UPDATE: 'docs:update',
  DOCS_DELETE: 'docs:delete',
  // registre des achats
  REGISTRE_EXPORT: 'registre:export',
  // profitability
  PROFIT_SUMMARY: 'profit:summary',
  // audit log (global)
  AUDIT_LIST_FOR: 'audit:listFor',
  AUDIT_RECENT: 'audit:recent',
  AUDIT_REVERT: 'audit:revert',
  // backup
  BACKUP_RUN: 'backup:run',
  BACKUP_LIST: 'backup:list',
  BACKUP_EXPORT: 'backup:export',
  // cloud sync (folder-based)
  CLOUD_STATUS: 'cloud:status',
  CLOUD_PICK_FOLDER: 'cloud:pickFolder',
  CLOUD_SAVE_CONFIG: 'cloud:saveConfig',
  CLOUD_SYNC_NOW: 'cloud:syncNow',
  CLOUD_OPEN_FOLDER: 'cloud:openFolder',
  CLOUD_SAVE_OPTIONS: 'cloud:saveOptions',
  CLOUD_SYNC_DOCS: 'cloud:syncDocs',
  CLOUD_SYNC_MOBILE: 'cloud:syncMobile',
  // seuils
  SEUILS_STATUS: 'seuils:status',
  // reminders
  REMINDERS_LIST: 'reminders:list',
  REMINDERS_DISMISS: 'reminders:dismiss',
  // PDF
  PDF_FACTURE: 'pdf:facture',
  PDF_DECLARATION_RECAP: 'pdf:declarationRecap',
  PDF_JUSTIFICATIF_ACHAT: 'pdf:justificatifAchat',
  PDF_JUSTIFICATIFS_BULK: 'pdf:justificatifsBulk',
  // XLSX
  XLSX_RECETTES: 'xlsx:recettes',
  // OCR
  OCR_PDF: 'ocr:pdf',
  // Bank + reconciliation
  BANK_IMPORT_PICK: 'bank:importPick',
  BANK_IMPORT_RUN: 'bank:importRun',
  BANK_TX_LIST: 'bank:txList',
  RECON_PARSE: 'recon:parse',
  RECON_MATCH: 'recon:match',
  // Diary
  DIARY_LIST: 'diary:list',
  DIARY_CREATE: 'diary:create',
  DIARY_UPDATE: 'diary:update',
  DIARY_DELETE: 'diary:delete',
  // First-run wizard
  WIZARD_NEEDED: 'wizard:needed',
  // Maintenance
  MAINT_RECLASSIFY_ALL: 'maint:reclassifyAll',
  MAINT_RESET: 'maint:reset',
  MAINT_EXPORT_JSON: 'maint:exportJson',
  MAINT_EXPORT_JSON_ANON: 'maint:exportJsonAnon',
  MAINT_EXPORT_JSON_ENCRYPTED: 'maint:exportJsonEncrypted',
  MAINT_ROTATE_AUDIT: 'maint:rotateAudit',
  // Security / privacy / future sync
  SECURITY_STATUS: 'security:status',
  SECURITY_SAVE_OPTIONS: 'security:saveOptions',
  SECURITY_BACKUP_ENCRYPTED: 'security:backupEncrypted',
  SECURITY_EXPORT_ANON: 'security:exportAnon',
  SECURITY_EXPORT_ENCRYPTED: 'security:exportEncrypted',
  SECURITY_PICK_ENCRYPTED_FILE: 'security:pickEncryptedFile',
  SECURITY_TEST_ENCRYPTED_FILE: 'security:testEncryptedFile',
  SECURITY_TEST_PASSPHRASE: 'security:testPassphrase',
  SECURITY_MOBILE_SNAPSHOT: 'security:mobileSnapshot',
  MOBILE_EXPORT_JSON_SNAPSHOT: 'mobile:exportJsonSnapshot',
  MOBILE_PICK_ACTIONS_FILE: 'mobile:pickActionsFile',
  MOBILE_PREVIEW_ACTIONS: 'mobile:previewActions',
  MOBILE_APPLY_ACTIONS: 'mobile:applyActions',
  MOBILE_LIST_ACTION_IMPORTS: 'mobile:listActionImports',
  SECURITY_CHECK_BACKUPS: 'security:checkBackups',
  SECURITY_CLEAN_TEMP: 'security:cleanTemp',
  SECURITY_OPEN_BACKUPS: 'security:openBackups',
  SECURITY_OPEN_EXPORTS: 'security:openExports',
  SECURITY_OPEN_SNAPSHOTS: 'security:openSnapshots',
  SYNC_OVERVIEW: 'sync:overview',
  // Analytics
  ANALYTICS_TRENDS: 'analytics:trends',
  ANALYTICS_TOP_BUYERS: 'analytics:topBuyers',
  ANALYTICS_STALE_STOCK: 'analytics:staleStock',
  ANALYTICS_PREDICTION: 'analytics:prediction',
  // Usability phase 2
  REVIEW_SUMMARY: 'review:summary',
  REVIEW_MARK: 'review:mark',
  REVIEW_MARK_BULK: 'review:markBulk',
  SAVED_FILTERS_LIST: 'savedFilters:list',
  SAVED_FILTERS_CREATE: 'savedFilters:create',
  SAVED_FILTERS_UPDATE: 'savedFilters:update',
  SAVED_FILTERS_DELETE: 'savedFilters:delete',
  GLOBAL_SEARCH: 'search:global',
  MARKETPLACES_LIST: 'marketplaces:list',
  MARKETPLACES_UPDATE: 'marketplaces:update',
  CHANNELS_LIST: 'channels:list',
  CHANNELS_UPSERT: 'channels:upsert',
  SUPPLIERS_LIST: 'suppliers:list',
  SUPPLIERS_UPSERT: 'suppliers:upsert',
  CSV_TEMPLATES_LIST: 'csvTemplates:list',
  CSV_TEMPLATES_CREATE: 'csvTemplates:create',
  CSV_TEMPLATES_UPDATE: 'csvTemplates:update',
  CSV_TEMPLATES_DELETE: 'csvTemplates:delete',
  BULK_MARK_VERIFIED: 'bulk:markVerified',
  BULK_SALES_CLASSIFY: 'bulk:salesClassify',
  BULK_STOCK_LOCATION: 'bulk:stockLocation',
  BULK_STOCK_STATUS: 'bulk:stockStatus',
  BULK_STOCK_MOVE_OUT: 'bulk:stockMoveOut',
  BULK_EXPENSE_CATEGORY: 'bulk:expenseCategory',
  BULK_DOCUMENT_TYPE: 'bulk:documentType',
  // CFE
  CFE_LIST: 'cfe:list',
  CFE_UPSERT: 'cfe:upsert',
  CFE_DELETE: 'cfe:delete',
  // Document links bulk lookup (avoid N+1)
  DOCS_LINKS_BULK: 'docs:linksBulk',
  // Templates CSV (download empty templates)
  TEMPLATE_STOCK_CSV: 'template:stockCsv',
  TEMPLATE_EXPENSES_CSV: 'template:expensesCsv',
  // Dashboard
  DASHBOARD_FIGURES: 'dashboard:figures',
  DASHBOARD_MARK_CHECK: 'dashboard:markCheck',
  // Agenda iCal
  AGENDA_EXPORT_ICS: 'agenda:exportIcs',
  // Imports for PDF (sale invoices, AliExpress purchase invoices)
  IMPORTS_PDF_SALES_PICK: 'imports:pdfSalesPick',
  IMPORTS_PDF_PURCHASES_PICK: 'imports:pdfPurchasesPick',
  IMPORTS_PDF_BOOSTS_PICK: 'imports:pdfBoostsPick',
  // Attach receipt to expense
  EXPENSE_ATTACH_RECEIPT: 'expense:attachReceipt',
  // misc
  APP_OPEN_DATA_FOLDER: 'app:openDataFolder',
  APP_OPEN_DOCS_FOLDER: 'app:openDocsFolder',
  APP_VERSION: 'app:version'
} as const;

export type IpcChannel = (typeof IPC)[keyof typeof IPC];
